### ISSUE TITLE
Consider implementing infix commands like `\over` and `\choose`

### ISSUE THREAD

**Issue by tmke8** [tmke8/latex2mmlc#60]
It would basically work like `^` and `_` work now: a node is parsed and then we check whether the next token is  `\over` or `\choose`, in which case we don't return the node yet and continue parsing.

Though, you actually get a warning if you use these in LaTeX today, so there's probably a good reason why you shouldn't use them.

**Comment by tmke8** [comment]
I don't think I will do this after all. It certainly would be possible to support, but I don't really see the point.

**Comment by csnover** [comment]
I have been using math-core in [wiki.rs](https://github.com/csnover/wiki.rs) and it has been delightful to see more equations start rendering over time as you have been making progress! Unfortunately, quite a lot of of the LaTeX on Wikipedia uses the `\over` command, so many pages are broken without it.

I would not consider my silly toy project to be important enough for anyone to care, but I figured I’d mention this use case, since it seemed like there was some uncertainty as to why anyone would ever need to use these commands in the first place.

In any case, thank you for your work on this library! It is a great mercy that this is one parser that I *didn’t* have to implement myself. :-)

**Comment by tmke8** [comment]
Thanks, it's indeed good to now that someone (i.e., Wikipedia) uses these commands.

The main problem is that I think this requires some kind of back-tracking functionality in the parser, which it currently doesn't have:

```tex
{\log x + a^n - \sin(\theta+\eta) \over x}
%                                 ^ oops, there is an \over
```

And I don't really know how complicated it would be to implement this.

But anyway, I'll re-open this issue.

**Comment by tmke8** [comment]
Wait, thinking about it for 5 more minutes, I realized it doesn't require back-tracking after all. We can handle it pretty cleanly in [`parse_sequence`](https://github.com/tmke8/math-core/blob/4543bf19c0aed8eed9afcee7796db123b530587e/crates/math-core/src/parser.rs#L146) where if we encounter `\over`, we take the sequence we had so far and interpret it as the numerator.

**Note to self**:

Pseudo code:

```rust
fn parse_sequence(...) {
  let mut nodes = Vec::new();
  let mut numerator: Option<Vec<Node>> = None;
  while !sequence_end.matches(self.tokens.peek().token()) {
    let cur_tokloc = self.next_token();
    if matches!(cur_tokloc, Token::Over) {
      numerator = Some(std::mem::take(&mut nodes));
      continue;
    }
    // ...
  }
  if let Some(numerator) = numerator {
    // construct the `Frac` node here from `numerator` and `nodes`
  }
  // ...
}
```

Still needs error handling: only one `\over` is allowed per sequence (surprisingly strict for LaTeX! a nice surprise!)
